services:
    - type: web
      name: todo-app
      env: docker
      buildCommand: docker build -t todo-app .
      startCommand: docker run -p $PORT:80 todo-app
      envVars:
        - key: DATABASE_URL
          fromDatabase:
            name: todo-db
            property: connectionString

databases:
    - name: todo-db
      databaseName: todo
      plan: free
      ipAllowList: []